---
- name: "[Kafka] Ensure Kafka log directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ os_group }}"
    mode: '0755'
  loop: "{{ kafka_log_dirs.split(',') }}"

- name: "[Kafka] Create server.properties configuration file"
  ansible.builtin.template:
    src: server.properties.j2
    dest: "{{ kafka_install_dir }}/config/server.properties"
    owner: "{{ kafka_user }}"
    group: "{{ os_group }}"
    mode: '0644'
  notify: Restart Kafka
