---
# Kafka Broker 專屬變數 / Kafka Broker Specific Variables
kafka_version: "3.7.2"
kafka_download_url: "http://192.168.200.30:8080/repo/kafka_2.12-{{ kafka_version }}.tgz"
kafka_install_dir: "{{ global_install_dir }}/kafka"
kafka_user: kafka
zk_connection_string: "192.168.200.20:2181,192.168.200.21:2181,192.168.200.22:2181"
listeners_port: 9092
advertised_listeners_host: "PLAINTEXT://{{ ansible_host }}:{{ listeners_port }}"
num_network_threads: 3
num_io_threads: 8
log_retention_hours: 168
log_segment_bytes: 1073741824
message_max_bytes: 1048576
auto_create_topics_enable: false
default_replication_factor: 3
kafka_heap_opts: "-Xmx2G -Xms2G"
kafka_log_dirs: "{{ global_data_dir }}/kafka-logs"
